export enum Links {
  LOGIN = '/login',
  ADMIN = '/admin',

  ADMIN_BLOG = '/admin/blog',
  ADMIN_BLOG_CREATE = '/admin/blog/create',
  ADMIN_BLOG_EDIT = '/admin/blog/edit',
  ADMIN_LESSON_SCHEDULE = '/admin/lesson-schedule',
  ADMIN_LESSON_SCHEDULE_CREATE = '/admin/lesson-schedule/create',
  ADMIN_LESSON_SCHEDULE_EDIT = '/admin/lesson-schedule/edit',
  ADMIN_SERVICES = '/admin/services',
  ADMIN_SERVICES_CREATE = '/admin/services/create',
  ADMIN_SERVICES_EDIT = '/admin/services/edit',

  ADMIN_PAGES = '/admin/pages',
  ADMIN_PAGES_ABOUT_COURSE = '/admin/pages/about-course',
  ADMIN_PAGES_BLOG = '/admin/pages/blog',
  ADMIN_PAGES_COMPANY = '/admin/pages/company',
  ADMIN_PAGES_CONTACT = '/admin/pages/contact',
  ADMIN_PAGES_PRICE = '/admin/pages/price',
  ADMIN_PAGES_SCHEDULE = '/admin/pages/schedule',
  ADMIN_PAGES_SETTINGS = '/admin/pages/settings',
  ADMIN_PAGES_HOME_SECTION_HERO = '/admin/pages/home/section-hero',
  ADMIN_PAGES_HOME_SECTION_ABOUT_US = '/admin/pages/home/section-about-us',
  ADMIN_PAGES_HOME_SECTION_ABOUT_COURSE = '/admin/pages/home/section-about-course',
  ADMIN_PAGES_HOME_SECTION_FORMAT_LESSONS = '/admin/pages/home/section-format-lessons',
  ADMIN_PAGES_HOME_SECTION_FAQ = '/admin/pages/home/section-faq',
  ADMIN_PAGES_HOME_SECTION_ACHIVMENTS = '/admin/pages/home/section-achivments',

  ADMIN_PAGE_SECTION_ACHIVMENTS = '/admin/page-sections/achivments',
  ADMIN_PAGE_SECTION_CONTACTS = '/admin/page-sections/contacts',
  ADMIN_PAGE_SECTION_REVIEW = '/admin/page-sections/review',
  ADMIN_PAGE_SECTION_CTA = '/admin/page-sections/cta',
  ADMIN_PAGE_SECTION_FAQ = '/admin/page-sections/faq',
}
