export enum BlocsEnum {
  BlockHero = 'BlockHero',
  BlockAboutCourse = 'BlockAboutCourse',
  BlockAboutUs = 'BlockAboutUs',
  BlockFormatLessons = 'BlockFormatLessons',
  BlockFaq = 'BlockFaq',
  BaseBlockFaq = 'BaseBlockFaq',
  BlockAchivments = 'BlockAchivments',
  BlockServices = 'BlockServices',
  BlockTeamEducation = 'BlockTeamEducation',
  BlockRequirement = 'BlockRequirement',
  BlockContacts = 'BlockContacts',
  BlockCourseForPeople = 'BlockCourseForPeople',
  BlockCta = 'BlockCta',
  BlockOurBenefits = 'BlockOurBenefits',
  BlockStructEducation = 'BlockStructEducation',
  BlockWhoTeach = 'BlockWhoTeach',
  BlockSchedule = 'BlockSchedule',
  BlockAbout = 'BlockAbout',
  BlockReview = 'BlockReview',
  BlockBlog = 'BlockBlog',
  BlockContactForm = 'BlockContactForm',
}
